-- CLEANUP (not shown in report - makes the demo re-runnable)
SET ECHO OFF
SET FEEDBACK OFF
SET HEADING OFF
SET TERMOUT OFF
WHENEVER SQLERROR CONTINUE
DROP VIEW v_account_summary;
DROP TABLE transaction CASCADE CONSTRAINTS;
DROP TABLE account CASCADE CONSTRAINTS;
DROP TABLE customer CASCADE CONSTRAINTS;
DROP PROCEDURE deposit_funds;
DROP PROCEDURE withdraw_funds;
DROP PROCEDURE open_account;
DROP SEQUENCE seq_txn;
DROP SEQUENCE seq_acct;
SET TERMOUT ON
